# Generated by Django 3.2.25 on 2026-07-31 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20260731_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='staus',
            new_name='status',
        ),
    ]
